<?php


/**
 * This class defines the structure of the 'formrow' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Sep  3 19:54:02 2012
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.zeusCorePlugin.lib.model.map
 */
class FormrowTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.zeusCorePlugin.lib.model.map.FormrowTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('formrow');
		$this->setPhpName('Formrow');
		$this->setClassname('Formrow');
		$this->setPackage('plugins.zeusCorePlugin.lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addColumn('TITLE', 'Title', 'VARCHAR', false, 255, null);
		$this->addForeignKey('FORM_ID', 'FormId', 'INTEGER', 'form', 'ID', false, null, null);
		$this->addColumn('RTYPE', 'Rtype', 'VARCHAR', false, 8, null);
		$this->addColumn('RVALIDATOR', 'Rvalidator', 'VARCHAR', false, 8, null);
		$this->addColumn('RVALIDATORVALUE', 'Rvalidatorvalue', 'LONGVARCHAR', false, null, null);
		$this->addColumn('RVALUE', 'Rvalue', 'LONGVARCHAR', false, null, null);
		$this->addColumn('ROPTIONS', 'Roptions', 'LONGVARCHAR', false, null, null);
		$this->addColumn('RREQUIRED', 'Rrequired', 'BOOLEAN', false, null, null);
		$this->addColumn('TABINDEX', 'Tabindex', 'INTEGER', false, null, null);
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Form', 'Form', RelationMap::MANY_TO_ONE, array('form_id' => 'id', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // FormrowTableMap
