<?php


/**
 * This class defines the structure of the 'menu' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Sep  3 19:54:02 2012
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.zeusCorePlugin.lib.model.map
 */
class MenuTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.zeusCorePlugin.lib.model.map.MenuTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('menu');
		$this->setPhpName('Menu');
		$this->setClassname('Menu');
		$this->setPackage('plugins.zeusCorePlugin.lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addColumn('TYPE', 'Type', 'VARCHAR', false, 8, null);
		$this->addColumn('VALUE', 'Value', 'VARCHAR', false, 128, null);
		$this->addColumn('TREE_PARENT', 'TreeParent', 'INTEGER', false, null, null);
		$this->addColumn('TREE_LEFT', 'TreeLeft', 'INTEGER', false, null, null);
		$this->addColumn('TREE_RIGHT', 'TreeRight', 'INTEGER', false, null, null);
		$this->addColumn('SCOPE', 'Scope', 'INTEGER', false, null, null);
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('MenuI18N', 'MenuI18N', RelationMap::ONE_TO_MANY, array('id' => 'id', ), 'CASCADE', null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
			'symfony_i18n' => array('i18n_table' => 'menu_i18n', ),
		);
	} // getBehaviors()

} // MenuTableMap
