<?php


/**
 * This class defines the structure of the 'user' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Jul  8 12:03:35 2013
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.zeusCorePlugin.lib.model.map
 */
class UserTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.zeusCorePlugin.lib.model.map.UserTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('user');
		$this->setPhpName('User');
		$this->setClassname('User');
		$this->setPackage('plugins.zeusCorePlugin.lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addColumn('TITLE', 'Title', 'VARCHAR', false, 64, null);
		$this->addColumn('USERNAME', 'Username', 'VARCHAR', false, 64, null);
		$this->addColumn('PASSWORD', 'Password', 'VARCHAR', false, 128, null);
		$this->addColumn('SALT', 'Salt', 'VARCHAR', false, 64, null);
		$this->addColumn('HASH', 'Hash', 'VARCHAR', false, 32, null);
		$this->addColumn('EMAIL', 'Email', 'VARCHAR', false, 64, null);
		$this->addColumn('CURRENTLOGIN', 'Currentlogin', 'TIMESTAMP', false, null, null);
		$this->addColumn('LASTLOGIN', 'Lastlogin', 'TIMESTAMP', false, null, null);
		$this->addColumn('IP', 'Ip', 'VARCHAR', false, 16, null);
		$this->addColumn('LASTIP', 'Lastip', 'VARCHAR', false, 16, null);
		$this->addColumn('SCRAPS', 'Scraps', 'LONGVARCHAR', false, null, null);
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Partner', 'Partner', RelationMap::ONE_TO_MANY, array('id' => 'user_id', ), null, null);
    $this->addRelation('Customer', 'Customer', RelationMap::ONE_TO_MANY, array('id' => 'user_id', ), null, null);
    $this->addRelation('Consumer', 'Consumer', RelationMap::ONE_TO_MANY, array('id' => 'user_id', ), null, null);
    $this->addRelation('Resource', 'Resource', RelationMap::ONE_TO_MANY, array('id' => 'user_id', ), null, null);
    $this->addRelation('CustomerSetting', 'CustomerSetting', RelationMap::ONE_TO_MANY, array('id' => 'user_id', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // UserTableMap
