<?php


/**
 * Skeleton subclass for representing a row from the 'bak_subscription' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Nov 29 15:53:15 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.zeusMailingPlugin.lib.model
 */
class BakSubscription extends BaseBakSubscription {

} // BakSubscription
