<?php


/**
 * Skeleton subclass for performing query and update operations on the 'mailinguser' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Jan  3 11:06:12 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.zeusMailingPlugin.lib.model
 */
class MailinguserPeer extends BaseMailinguserPeer {

} // MailinguserPeer
