<?php



/**
 * Skeleton subclass for performing query and update operations on the 'mailing_subscription' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3-dev on:
 *
 * Fri Oct 14 12:20:22 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.zeusMailingPlugin.lib.model
 */
class MailingSubscriptionQuery extends BaseMailingSubscriptionQuery {

} // MailingSubscriptionQuery
