prod:
  .settings:
    no_script_name:         true
    logging_enabled:        true

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    logging_enabled:        true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .actions:
    error_404_module:       error  
    error_404_action:       error404
    login_module:           admin
    login_action:           login

  .settings:
    # Form security secret (CSRF protection)
    #csrf_secret:       b9d0f1a762c996616d05cb03bb739ba4c06a20f6     # Unique secret to enable CSRF protection or false to disable
    csrf_secret: false
    
    # Output escaping settings
    escaping_strategy:      false            # Determines how variables are made available to templates. Accepted values: true, false.
    escaping_method:        ESC_SPECIALCHARS # Function or helper used for escaping. Accepted values: ESC_RAW, ESC_ENTITIES, ESC_JS, ESC_JS_NO_ENTITIES, and ESC_SPECIALCHARS.

    # Cache settings
    lazy_cache_key:         true        # Delays creation of a cache key until after checking whether an action or partial is cacheable
    
    standard_helpers:       [Partial, Cache, Form, ZeusRoute, I18N]
    enabled_modules:
      - default
      - sfGuardAuth
      - sfGuardGroup
      - sfGuardUser
      - sfGuardPermission
      - sfGuardModule
      - page
      - news
      - files
      - form
      - menu
      - events
      - captcha
      - search
      - sitemap
      - jobs
      - rss
      - core
      - mailing
      - mailingadmin
      - filesadmin
      - sfCombine
      
    default_culture:  nl_NL
    enabled_cultures: [ nl_NL, en_US ]
    i18n:             off
    use_fallback:     true


