default:
  http_metas:
    content-type: text/html

  metas:
    title:                    iWerkbon

  stylesheets:   
    - /css/normalize.css
    - /css/iwerkbon-screen.css
    - http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css
    - /css/forms.css

  javascripts:
    - /zeusCore/js/prototype/prototype.js
    - /zeusCore/js/scriptaculous/scriptaculous.js
    - /zeusCore/js/scriptaculous/effects.js
    - https://maps.googleapis.com/maps/api/js?key=AIzaSyAyzweGvEwL6B_J_TD2GkAm901lHUeD4kU
    - /js/admin.js
    - /js/iwerkbon.js

  has_layout:     true
  layout:         layout

  
