<?php


/**
 * Skeleton subclass for representing a row from the 'sf_combine' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Apr  2 13:22:38 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.sfCombinePlugin.lib.model
 */
class sfCombine extends BasesfCombine {

} // sfCombine
