<?php


/**
 * This class defines the structure of the 'bak_subscription' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Jul  8 12:03:38 2013
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.zeusMailingPlugin.lib.model.map
 */
class BakSubscriptionTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.zeusMailingPlugin.lib.model.map.BakSubscriptionTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('bak_subscription');
		$this->setPhpName('BakSubscription');
		$this->setClassname('BakSubscription');
		$this->setPackage('plugins.zeusMailingPlugin.lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addForeignKey('BAK_MAILINGUSER_ID', 'BakMailinguserId', 'INTEGER', 'bak_mailinguser', 'ID', false, null, null);
		$this->addForeignKey('MAILINGLIST_ID', 'MailinglistId', 'INTEGER', 'mailinglist', 'ID', false, null, null);
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('BakMailinguser', 'BakMailinguser', RelationMap::MANY_TO_ONE, array('bak_mailinguser_id' => 'id', ), null, null);
    $this->addRelation('Mailinglist', 'Mailinglist', RelationMap::MANY_TO_ONE, array('mailinglist_id' => 'id', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // BakSubscriptionTableMap
