<?php


/**
 * Skeleton subclass for performing query and update operations on the 'appointment' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Oct  6 11:50:05 2015
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class AppointmentPeer extends BaseAppointmentPeer {

} // AppointmentPeer
