<?php


/**
 * Skeleton subclass for representing a row from the 'category' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Jul 23 11:26:09 2015
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Category extends BaseCategory {

} // Category

$columns_map = array(
  'left'   => CategoryPeer::TREE_LEFT,
  'right'  => CategoryPeer::TREE_RIGHT,
  'parent' => CategoryPeer::TREE_PARENT,
  'scope'  => CategoryPeer::TREE);

sfPropelBehavior::add('Category', array('zeusnestedset' => array('columns' => $columns_map)));