<?php


/**
 * Skeleton subclass for performing query and update operations on the 'field_value' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Oct 20 21:08:36 2015
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class FieldValuePeer extends BaseFieldValuePeer {

} // FieldValuePeer
