<?php


/**
 * Skeleton subclass for performing query and update operations on the 'landing_i18n' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Jul  2 13:28:18 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class LandingI18NPeer extends BaseLandingI18NPeer {

} // LandingI18NPeer
