<?php


/**
 * Skeleton subclass for performing query and update operations on the 'message' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu Apr  2 13:45:11 2015
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class MessagePeer extends BaseMessagePeer {

} // MessagePeer
