<?php


/**
 * Skeleton subclass for performing query and update operations on the 'partial' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Oct  5 16:06:59 2015
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class PartialPeer extends BasePartialPeer {

  public static function findByName($name)
  {
    $c = new Criteria;
    $c->add(PartialPeer::KEY, $name);
    $partial = PartialPeer::doSelectOne($c);
    return $partial;
  }
} // PartialPeer
