<?php


/**
 * Skeleton subclass for representing a row from the 'workorder' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Jul 20 16:18:50 2015
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Workorder extends BaseWorkorder {
  public function getStatusStr()
  {
    $status = $this->getStatus();
    $statusses = array(
      'started' => 'Gestart',
      'success' => 'Afgerond',
      'cancelled' => 'Geannuleerd',
      'scheduled' => 'Ingepland'
    );
    return $statusses[$status];
  }
} // Workorder
