<?php


/**
 * Base class that represents a query for the 'mailing' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.4-dev on:
 *
 * Wed May 16 11:52:32 2012
 *
 * @method     MailingQuery orderByTitle($order = Criteria::ASC) Order by the title column
 * @method     MailingQuery orderBySite($order = Criteria::ASC) Order by the site column
 * @method     MailingQuery orderByMailinglist($order = Criteria::ASC) Order by the mailinglist column
 * @method     MailingQuery orderByTemplate($order = Criteria::ASC) Order by the template column
 * @method     MailingQuery orderByContent($order = Criteria::ASC) Order by the content column
 * @method     MailingQuery orderByStatus($order = Criteria::ASC) Order by the status column
 * @method     MailingQuery orderByDate($order = Criteria::ASC) Order by the date column
 * @method     MailingQuery orderById($order = Criteria::ASC) Order by the id column
 *
 * @method     MailingQuery groupByTitle() Group by the title column
 * @method     MailingQuery groupBySite() Group by the site column
 * @method     MailingQuery groupByMailinglist() Group by the mailinglist column
 * @method     MailingQuery groupByTemplate() Group by the template column
 * @method     MailingQuery groupByContent() Group by the content column
 * @method     MailingQuery groupByStatus() Group by the status column
 * @method     MailingQuery groupByDate() Group by the date column
 * @method     MailingQuery groupById() Group by the id column
 *
 * @method     MailingQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method     MailingQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method     MailingQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method     MailingQuery leftJoinMailingSubscription($relationAlias = null) Adds a LEFT JOIN clause to the query using the MailingSubscription relation
 * @method     MailingQuery rightJoinMailingSubscription($relationAlias = null) Adds a RIGHT JOIN clause to the query using the MailingSubscription relation
 * @method     MailingQuery innerJoinMailingSubscription($relationAlias = null) Adds a INNER JOIN clause to the query using the MailingSubscription relation
 *
 * @method     Mailing findOne(PropelPDO $con = null) Return the first Mailing matching the query
 * @method     Mailing findOneOrCreate(PropelPDO $con = null) Return the first Mailing matching the query, or a new Mailing object populated from the query conditions when no match is found
 *
 * @method     Mailing findOneByTitle(string $title) Return the first Mailing filtered by the title column
 * @method     Mailing findOneBySite(string $site) Return the first Mailing filtered by the site column
 * @method     Mailing findOneByMailinglist(string $mailinglist) Return the first Mailing filtered by the mailinglist column
 * @method     Mailing findOneByTemplate(string $template) Return the first Mailing filtered by the template column
 * @method     Mailing findOneByContent(string $content) Return the first Mailing filtered by the content column
 * @method     Mailing findOneByStatus(string $status) Return the first Mailing filtered by the status column
 * @method     Mailing findOneByDate(string $date) Return the first Mailing filtered by the date column
 * @method     Mailing findOneById(int $id) Return the first Mailing filtered by the id column
 *
 * @method     array findByTitle(string $title) Return Mailing objects filtered by the title column
 * @method     array findBySite(string $site) Return Mailing objects filtered by the site column
 * @method     array findByMailinglist(string $mailinglist) Return Mailing objects filtered by the mailinglist column
 * @method     array findByTemplate(string $template) Return Mailing objects filtered by the template column
 * @method     array findByContent(string $content) Return Mailing objects filtered by the content column
 * @method     array findByStatus(string $status) Return Mailing objects filtered by the status column
 * @method     array findByDate(string $date) Return Mailing objects filtered by the date column
 * @method     array findById(int $id) Return Mailing objects filtered by the id column
 *
 * @package    propel.generator.plugins.zeusMailingPlugin.lib.model.om
 */
abstract class BaseMailingQuery extends ModelCriteria
{
	
	/**
	 * Initializes internal state of BaseMailingQuery object.
	 *
	 * @param     string $dbName The dabase name
	 * @param     string $modelName The phpName of a model, e.g. 'Book'
	 * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
	 */
	public function __construct($dbName = 'propel', $modelName = 'Mailing', $modelAlias = null)
	{
		parent::__construct($dbName, $modelName, $modelAlias);
	}

	/**
	 * Returns a new MailingQuery object.
	 *
	 * @param     string $modelAlias The alias of a model in the query
	 * @param     Criteria $criteria Optional Criteria to build the query from
	 *
	 * @return    MailingQuery
	 */
	public static function create($modelAlias = null, $criteria = null)
	{
		if ($criteria instanceof MailingQuery) {
			return $criteria;
		}
		$query = new MailingQuery();
		if (null !== $modelAlias) {
			$query->setModelAlias($modelAlias);
		}
		if ($criteria instanceof Criteria) {
			$query->mergeWith($criteria);
		}
		return $query;
	}

	/**
	 * Find object by primary key.
	 * Propel uses the instance pool to skip the database if the object exists.
	 * Go fast if the query is untouched.
	 *
	 * <code>
	 * $obj  = $c->findPk(12, $con);
	 * </code>
	 *
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    Mailing|array|mixed the result, formatted by the current formatter
	 */
	public function findPk($key, $con = null)
	{
		if ($key === null) {
			return null;
		}
		if ((null !== ($obj = MailingPeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
			// the object is alredy in the instance pool
			return $obj;
		}
		if ($con === null) {
			$con = Propel::getConnection(MailingPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
		$this->basePreSelect($con);
		if ($this->formatter || $this->modelAlias || $this->with || $this->select
		 || $this->selectColumns || $this->asColumns || $this->selectModifiers
		 || $this->map || $this->having || $this->joins) {
			return $this->findPkComplex($key, $con);
		} else {
			return $this->findPkSimple($key, $con);
		}
	}

	/**
	 * Find object by primary key using raw SQL to go fast.
	 * Bypass doSelect() and the object formatter by using generated code.
	 *
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con A connection object
	 *
	 * @return    Mailing A model object, or null if the key is not found
	 */
	protected function findPkSimple($key, $con)
	{
		$sql = 'SELECT `TITLE`, `SITE`, `MAILINGLIST`, `TEMPLATE`, `CONTENT`, `STATUS`, `DATE`, `ID` FROM `mailing` WHERE `ID` = :p0';
		try {
			$stmt = $con->prepare($sql);
			$stmt->bindValue(':p0', $key, PDO::PARAM_INT);
			$stmt->execute();
		} catch (Exception $e) {
			Propel::log($e->getMessage(), Propel::LOG_ERR);
			throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
		}
		$obj = null;
		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$obj = new Mailing();
			$obj->hydrate($row);
			MailingPeer::addInstanceToPool($obj, (string) $row[0]);
		}
		$stmt->closeCursor();

		return $obj;
	}

	/**
	 * Find object by primary key.
	 *
	 * @param     mixed $key Primary key to use for the query
	 * @param     PropelPDO $con A connection object
	 *
	 * @return    Mailing|array|mixed the result, formatted by the current formatter
	 */
	protected function findPkComplex($key, $con)
	{
		// As the query uses a PK condition, no limit(1) is necessary.
		$criteria = $this->isKeepQuery() ? clone $this : $this;
		$stmt = $criteria
			->filterByPrimaryKey($key)
			->doSelect($con);
		return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
	}

	/**
	 * Find objects by primary key
	 * <code>
	 * $objs = $c->findPks(array(12, 56, 832), $con);
	 * </code>
	 * @param     array $keys Primary keys to use for the query
	 * @param     PropelPDO $con an optional connection object
	 *
	 * @return    PropelObjectCollection|array|mixed the list of results, formatted by the current formatter
	 */
	public function findPks($keys, $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
		}
		$this->basePreSelect($con);
		$criteria = $this->isKeepQuery() ? clone $this : $this;
		$stmt = $criteria
			->filterByPrimaryKeys($keys)
			->doSelect($con);
		return $criteria->getFormatter()->init($criteria)->format($stmt);
	}

	/**
	 * Filter the query by primary key
	 *
	 * @param     mixed $key Primary key to use for the query
	 *
	 * @return    MailingQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKey($key)
	{
		return $this->addUsingAlias(MailingPeer::ID, $key, Criteria::EQUAL);
	}

	/**
	 * Filter the query by a list of primary keys
	 *
	 * @param     array $keys The list of primary key to use for the query
	 *
	 * @return    MailingQuery The current query, for fluid interface
	 */
	public function filterByPrimaryKeys($keys)
	{
		return $this->addUsingAlias(MailingPeer::ID, $keys, Criteria::IN);
	}

	/**
	 * Filter the query on the title column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByTitle('fooValue');   // WHERE title = 'fooValue'
	 * $query->filterByTitle('%fooValue%'); // WHERE title LIKE '%fooValue%'
	 * </code>
	 *
	 * @param     string $title The value to use as filter.
	 *              Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MailingQuery The current query, for fluid interface
	 */
	public function filterByTitle($title = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($title)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $title)) {
				$title = str_replace('*', '%', $title);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(MailingPeer::TITLE, $title, $comparison);
	}

	/**
	 * Filter the query on the site column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterBySite('fooValue');   // WHERE site = 'fooValue'
	 * $query->filterBySite('%fooValue%'); // WHERE site LIKE '%fooValue%'
	 * </code>
	 *
	 * @param     string $site The value to use as filter.
	 *              Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MailingQuery The current query, for fluid interface
	 */
	public function filterBySite($site = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($site)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $site)) {
				$site = str_replace('*', '%', $site);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(MailingPeer::SITE, $site, $comparison);
	}

	/**
	 * Filter the query on the mailinglist column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByMailinglist('fooValue');   // WHERE mailinglist = 'fooValue'
	 * $query->filterByMailinglist('%fooValue%'); // WHERE mailinglist LIKE '%fooValue%'
	 * </code>
	 *
	 * @param     string $mailinglist The value to use as filter.
	 *              Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MailingQuery The current query, for fluid interface
	 */
	public function filterByMailinglist($mailinglist = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($mailinglist)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $mailinglist)) {
				$mailinglist = str_replace('*', '%', $mailinglist);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(MailingPeer::MAILINGLIST, $mailinglist, $comparison);
	}

	/**
	 * Filter the query on the template column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByTemplate('fooValue');   // WHERE template = 'fooValue'
	 * $query->filterByTemplate('%fooValue%'); // WHERE template LIKE '%fooValue%'
	 * </code>
	 *
	 * @param     string $template The value to use as filter.
	 *              Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MailingQuery The current query, for fluid interface
	 */
	public function filterByTemplate($template = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($template)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $template)) {
				$template = str_replace('*', '%', $template);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(MailingPeer::TEMPLATE, $template, $comparison);
	}

	/**
	 * Filter the query on the content column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByContent('fooValue');   // WHERE content = 'fooValue'
	 * $query->filterByContent('%fooValue%'); // WHERE content LIKE '%fooValue%'
	 * </code>
	 *
	 * @param     string $content The value to use as filter.
	 *              Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MailingQuery The current query, for fluid interface
	 */
	public function filterByContent($content = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($content)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $content)) {
				$content = str_replace('*', '%', $content);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(MailingPeer::CONTENT, $content, $comparison);
	}

	/**
	 * Filter the query on the status column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByStatus('fooValue');   // WHERE status = 'fooValue'
	 * $query->filterByStatus('%fooValue%'); // WHERE status LIKE '%fooValue%'
	 * </code>
	 *
	 * @param     string $status The value to use as filter.
	 *              Accepts wildcards (* and % trigger a LIKE)
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MailingQuery The current query, for fluid interface
	 */
	public function filterByStatus($status = null, $comparison = null)
	{
		if (null === $comparison) {
			if (is_array($status)) {
				$comparison = Criteria::IN;
			} elseif (preg_match('/[\%\*]/', $status)) {
				$status = str_replace('*', '%', $status);
				$comparison = Criteria::LIKE;
			}
		}
		return $this->addUsingAlias(MailingPeer::STATUS, $status, $comparison);
	}

	/**
	 * Filter the query on the date column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterByDate('2011-03-14'); // WHERE date = '2011-03-14'
	 * $query->filterByDate('now'); // WHERE date = '2011-03-14'
	 * $query->filterByDate(array('max' => 'yesterday')); // WHERE date > '2011-03-13'
	 * </code>
	 *
	 * @param     mixed $date The value to use as filter.
	 *              Values can be integers (unix timestamps), DateTime objects, or strings.
	 *              Empty strings are treated as NULL.
	 *              Use scalar values for equality.
	 *              Use array values for in_array() equivalent.
	 *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MailingQuery The current query, for fluid interface
	 */
	public function filterByDate($date = null, $comparison = null)
	{
		if (is_array($date)) {
			$useMinMax = false;
			if (isset($date['min'])) {
				$this->addUsingAlias(MailingPeer::DATE, $date['min'], Criteria::GREATER_EQUAL);
				$useMinMax = true;
			}
			if (isset($date['max'])) {
				$this->addUsingAlias(MailingPeer::DATE, $date['max'], Criteria::LESS_EQUAL);
				$useMinMax = true;
			}
			if ($useMinMax) {
				return $this;
			}
			if (null === $comparison) {
				$comparison = Criteria::IN;
			}
		}
		return $this->addUsingAlias(MailingPeer::DATE, $date, $comparison);
	}

	/**
	 * Filter the query on the id column
	 *
	 * Example usage:
	 * <code>
	 * $query->filterById(1234); // WHERE id = 1234
	 * $query->filterById(array(12, 34)); // WHERE id IN (12, 34)
	 * $query->filterById(array('min' => 12)); // WHERE id > 12
	 * </code>
	 *
	 * @param     mixed $id The value to use as filter.
	 *              Use scalar values for equality.
	 *              Use array values for in_array() equivalent.
	 *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MailingQuery The current query, for fluid interface
	 */
	public function filterById($id = null, $comparison = null)
	{
		if (is_array($id) && null === $comparison) {
			$comparison = Criteria::IN;
		}
		return $this->addUsingAlias(MailingPeer::ID, $id, $comparison);
	}

	/**
	 * Filter the query by a related MailingSubscription object
	 *
	 * @param     MailingSubscription $mailingSubscription  the related object to use as filter
	 * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
	 *
	 * @return    MailingQuery The current query, for fluid interface
	 */
	public function filterByMailingSubscription($mailingSubscription, $comparison = null)
	{
		if ($mailingSubscription instanceof MailingSubscription) {
			return $this
				->addUsingAlias(MailingPeer::ID, $mailingSubscription->getMailingId(), $comparison);
		} elseif ($mailingSubscription instanceof PropelCollection) {
			return $this
				->useMailingSubscriptionQuery()
				->filterByPrimaryKeys($mailingSubscription->getPrimaryKeys())
				->endUse();
		} else {
			throw new PropelException('filterByMailingSubscription() only accepts arguments of type MailingSubscription or PropelCollection');
		}
	}

	/**
	 * Adds a JOIN clause to the query using the MailingSubscription relation
	 *
	 * @param     string $relationAlias optional alias for the relation
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    MailingQuery The current query, for fluid interface
	 */
	public function joinMailingSubscription($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
	{
		$tableMap = $this->getTableMap();
		$relationMap = $tableMap->getRelation('MailingSubscription');

		// create a ModelJoin object for this join
		$join = new ModelJoin();
		$join->setJoinType($joinType);
		$join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
		if ($previousJoin = $this->getPreviousJoin()) {
			$join->setPreviousJoin($previousJoin);
		}

		// add the ModelJoin to the current object
		if($relationAlias) {
			$this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
			$this->addJoinObject($join, $relationAlias);
		} else {
			$this->addJoinObject($join, 'MailingSubscription');
		}

		return $this;
	}

	/**
	 * Use the MailingSubscription relation MailingSubscription object
	 *
	 * @see       useQuery()
	 *
	 * @param     string $relationAlias optional alias for the relation,
	 *                                   to be used as main alias in the secondary query
	 * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
	 *
	 * @return    MailingSubscriptionQuery A secondary query class using the current class as primary query
	 */
	public function useMailingSubscriptionQuery($relationAlias = null, $joinType = Criteria::LEFT_JOIN)
	{
		return $this
			->joinMailingSubscription($relationAlias, $joinType)
			->useQuery($relationAlias ? $relationAlias : 'MailingSubscription', 'MailingSubscriptionQuery');
	}

	/**
	 * Exclude object from result
	 *
	 * @param     Mailing $mailing Object to remove from the list of results
	 *
	 * @return    MailingQuery The current query, for fluid interface
	 */
	public function prune($mailing = null)
	{
		if ($mailing) {
			$this->addUsingAlias(MailingPeer::ID, $mailing->getId(), Criteria::NOT_EQUAL);
		}

		return $this;
	}

} // BaseMailingQuery