<?php


/**
 * Skeleton subclass for performing query and update operations on the 'support_ticket' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Jun 29 10:17:11 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.zeusCorePlugin.plugins.pvLogin.lib.model
 */
class SupportTicketPeer extends BaseSupportTicketPeer {

} // SupportTicketPeer
