<?php


/**
 * Skeleton subclass for representing a row from the 'changelog' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Nov 30 18:29:19 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.zeusCorePlugin.lib.model
 */
class Changelog extends BaseChangelog {

  public static function add($title, $change_type, $object = null, $action_url = null)
  {
    $change = new Changelog;
    $change->setTitle($title);
    $change->setCtype($change_type);
    
    if ($object) {
      $change->setObject(get_class($object));
      $change->setObjectId($object->getId());
    }
    
    if ($action_url) {
      $change->setActionurl($action_url);
    }
    
    $change->save();
  }
} // Changelog
