<?php


/**
 * Skeleton subclass for representing a row from the 'favorite' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Dec  1 13:49:44 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.zeusCorePlugin.lib.model
 */
class Favorite extends BaseFavorite {

} // Favorite
