<?php


/**
 * Skeleton subclass for performing query and update operations on the 'news_i18n' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Sep  3 19:54:03 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.zeusCorePlugin.lib.model
 */
class NewsI18NPeer extends BaseNewsI18NPeer {

} // NewsI18NPeer
