<?php


/**
 * Skeleton subclass for representing a row from the 'support_reply' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Dec  1 12:45:22 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.zeusCorePlugin.lib.model
 */
class SupportReply extends BaseSupportReply {

} // SupportReply
