<?php


/**
 * Skeleton subclass for representing a row from the 'ugroup' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Nov 30 12:34:26 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.zeusCorePlugin.lib.model
 */
class Ugroup extends BaseUgroup {

} // Ugroup
